# Plugins
plugins             : ["jekyll-include-cache"]

#Theme
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title: Zentip
# subtitle: "Get tipped with new tickets"
description: "ZenTip - A chrome extension that notifies users when new replies or tickets are posted."
url: "https://neophoriac.github.io/zentip-website" # the base hostname & protocol for your site
baseurl: "/zentip-website" # the subpath of your site, e.g. /blog/
author:
  name: "Neophytos Gregoriou"
  bio: "Chrome Extension Developer"
  location: "Cyprus"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/neophoriac"
repository: "neophoriac/zentip-website"
logo: "/assets/images/zentip-logo.png"
search: true
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/neophoriac"