name: GitHub Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLIC_STATIC_FORMS_KEY: sf_ci_placeholder
    defaults:
      run:
        working-directory: astrowind
    strategy:
      matrix:
        node-version:
          - 22
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: astrowind/package-lock.json
      - run: npm ci
      - run: npm run build
      # - run: npm test

  check:
    runs-on: ubuntu-latest
    env:
      PUBLIC_STATIC_FORMS_KEY: sf_ci_placeholder
    defaults:
      run:
        working-directory: astrowind
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 22
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: astrowind/package-lock.json
      - run: npm ci
      - run: npm run check
